### ISSUE TITLE
Make explorer searchable

### ISSUE THREAD

**Issue by smathot** [dschreij/QOpenScienceFramework#14]
As I've used, and seen being used, the OSF extension more and more, it's become clear to me that some people have many, many projects. So it would be good to make the explorer searchable. I'm thinking about a simple search just above the tree widget that searches projects by title and contributor.

**Comment by dschreij** [comment]
Yes, I agree. The mechanics are already in place, as there already is a Tree Iterator implemented in some form that filters everything but .osexp files. Because this was out of scope at the time we worked on this extension in Marseille and it wasn't finished and had not been thoroughly tested yet, I have disabled this functionality, but it should be a good basis for a search function.

**Comment by dschreij** [comment]
This has been added in 1.3.0
