### ISSUE TITLE
Only retrieve contents when necessary

### ISSUE THREAD

**Issue by smathot** [dschreij/QOpenScienceFramework#17]
I now have a large number of OSF repositories. Because the OSF is quite slow, it takes a while for the entire tree to be built. Generally, I just want to retrieve one experiment from one repository, so retrieving all the other repositories is not necessary. Would it be possible to retrieve a repository only when the unfold button is clicked?

**Comment by dschreij** [comment]
Agreed. I had been thinking about that too at some point. The downside is that a search function becomes a lot harder, because all info is not readily available and needs to be pulled of the OSF server first. So the choice is between making data retrieval more efficient, or (some day) add a search box which can be used to search the item tree.

**Comment by smathot** [comment]
The search box could search only through the top-level items, so that it doesn't need to pull the entire structure from the OSF first. That's what you usually want, right? You have a whole bunch of projects and you quickly want to find the one that you're working on.

**Comment by dschreij** [comment]
I thought of it more like a folder, file/experiment based search, like the quickfind feature in OpenSesame. But searching only through top-level items should also work.

**Comment by dschreij** [comment]
This is fixed in 1.3.0
